[STRATO-1565] Compatibility with oauth
blockapps/blockapps-sol pull request #33
Opened 2019-08-14 16:18 UTC by Tanooj0902

2019-08-19 15:34 UTC, liorsaar1 requested changes

2019-08-19 15:34 UTC, liorsaar1 commented on lib/auth/user/test/user.test.js
> +    const user = await contract.getState(admin);
the contract object should encapsulate its creator `admin`.  any call to contract methods, like `contract.getState()`  should not have to provide the admin - it should already be there.

please change to:
`const user = await contract.getState()`;

2019-08-20 11:17 UTC, Tanooj0902 commented on lib/auth/user/test/user.test.js
> +    const user = await contract.getState(admin);
Fixed!!

2019-08-22 13:57 UTC, liorsaar1 requested changes
this will only work with the correct `blockapps-sol` version.
* please create the `peg` to the correct `blockapps-sol` ?
* please document in the release notes

2019-10-04 20:34 UTC, closed without merging